<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="eTouch-2.local" name="com.etouch.fox.common.TestCiscoMainPage" tests="2" failures="0" timestamp="11 Apr 2014 21:31:33 GMT" time="12.633" errors="1">
  <testcase name="testSignIn" time="8.079" classname="com.etouch.fox.common.TestCiscoMainPage">
    <error type="java.lang.AssertionError" message="URL did not matched expected [https://tools.cisco.com/wsrp/pwc019/mobile/view] but found [test]">
      <![CDATA[java.lang.AssertionError: URL did not matched expected [https://tools.cisco.com/wsrp/pwc019/mobile/view] but found [test]
	at org.testng.Assert.fail(Assert.java:94)
	at com.etouch.fox.common.pages.CommonPage.logAndCreateADefect(CommonPage.java:214)
	at com.etouch.fox.common.TestCiscoMainPage.testSignIn(TestCiscoMainPage.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.etouch.taf.core.TestBedManager.executeTestNG(TestBedManager.java:124)
	at com.etouch.fox.common.BaseTest.exceuteTestNGFile(BaseTest.java:141)
	at com.etouch.fox.common.BaseTest.main(BaseTest.java:102)
]]>
    </error>
  </testcase> <!-- testSignIn -->
  <testcase name="calCostPurchaseTab" time="4.554" classname="com.etouch.fox.common.TestCiscoMainPage"/>
</testsuite> <!-- com.etouch.fox.common.TestCiscoMainPage -->
